export const CREATION_STATUS = {
  CREATED: 'CREATED',
  DELETED: 'DELETED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
}

export const DATA_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
}

export const DATE_RANGE_TYPE = {
  ONE_DAYS: 'ONE_DAYS',
  ONE_WEAK: 'ONE_WEAK',
  FIFTEEN_DAYS: 'FIFTEEN_DAYS',
  ONE_MONTH: 'ONE_MONTH',
  THREE_MONTHS: 'THREE_MONTHS',
  SIX_MONTHS: 'SIX_MONTHS',
  ONE_YEAR: 'ONE_YEAR',
  MAX: 'MAX'
}

export const INFO_LOG_TYPE = {
  ERROR: 'ERROR',
  WARNING: 'WARNING',
  INFO: 'INFO',
  SYSTEM: 'SYSTEM',
  OTP: 'OTP',
  OTHERS: 'OTHERS',
  SEEDING: 'SEEDING'
}

export const MICROSERVICE_NAME_FOR_PORT = {
  ADMIN: 8080,
  AUTHENTICATION: 8081,
  CHAT: 8082,
  CORE: 8083,
  LIVENESS: 8084,
  PAYMENT: 8085,
  S3: 8086,
  SANCTION: 8087,
  SELLER: 8088,
  USER: 8089
}

export const MICROSERVICE_NAME = {
  ADMIN: "admin",
  AUTHENTICATION: "authentication",
  CHAT: "chat",
  CORE: "core",
  LIVENESS: "liveness",
  PAYMENT: "payment",
  S3: "s3",
  SANCTION: "sanction",
  SELLER: "seller",
  USER: "user"
}

export const RESPONSE_TYPE = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
}

export const SANCTION_TYPE = {
  AMS: 'AMS',
  PEP: 'PEP',
  AML: 'AML'
}

export const SELLER_ACCOUNT_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
  BANNED: 'BANNED',
  CLOSED: 'CLOSED',
}

export const STATUS = {
  UP: 'UP',
  DOWN: 'DOWN',
}

export const TIRE_CODE = {
  TIRE0: 'TIRE0',
  TIRE1: 'TIRE1',
  TIRE2: 'TIRE2',
  TIRE3: 'TIRE3',
  TIRE4: 'TIRE4',
}

export const USER_ROLE = {
  ROLE_MASTER: 'ROLE_MASTER',
  ROLE_CUSTOMER: 'ROLE_CUSTOMER',
  ROLE_SELLER: 'ROLE_SELLER',
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_DOCTOR: 'ROLE_DOCTOR',
  ROLE_RAIDER: 'ROLE_RAIDER',
  ROLE_DELIVERY_BOY: 'ROLE_DELIVERY_BOY',
  ROLE_CUSTOMER_CARE: 'ROLE_CUSTOMER_CARE',
  GUEST: 'GUEST'
}

export const VERIFICATION_TYPE_STATUS_FOR_LIVENESS = {
  LIVENESS_VERIFIED: 'LIVENESS_VERIFIED',
  LIVENESS_NOT_VERIFIED: 'LIVENESS_NOT_VERIFIED',
  LIVENESS_PENDING: 'LIVENESS_PENDING'
}

export const VERIFICATION_TYPE_STATUS_FOR_SANCTION = {
  SANCTION_VERIFIED: 'SANCTION_VERIFIED',
  SANCTION_NOT_VERIFIED: 'SANCTION_NOT_VERIFIED',
  SANCTION_PENDING: 'SANCTION_PENDING',
}


