export const exampleMenu =
  [
    {
        "id": "c7f5b7d2-a13c-42cd-88e1-356bf4734bfb",
        "menuName": "Home",
        "doHaveRedirectionLink": null,
        "menuLink": "/home",
        "isASubMenu": false,
        "canMasterAccess": null,
        "canAdminAccess": true,
        "canUserAccess": true,
        "canDoctorAccess": true,
        "canSellerAccess": true,
        "canRiderAccess": true,
        "chatUsersAccess": true,
        "isVisibleToGuest": true,
        "isAvailableWhileLoggedOut": true,
        "isAssignedToParentMenu": true,
        "listOfSubMenu": null
    },
    {
        "id": "ddfca568-af0c-4381-9824-9c630d9c2677",
        "menuName": "Admin",
        "doHaveRedirectionLink": null,
        "menuLink": null,
        "isASubMenu": false,
        "canMasterAccess": null,
        "canAdminAccess": true,
        "canUserAccess": true,
        "canDoctorAccess": true,
        "canSellerAccess": true,
        "canRiderAccess": true,
        "chatUsersAccess": true,
        "isVisibleToGuest": true,
        "isAvailableWhileLoggedOut": true,
        "isAssignedToParentMenu": true,
        "listOfSubMenu": [
            {
                "id": "f48e2629-5d1f-4fe9-a38e-a6aa74c8b5d5",
                "menuName": "Seller View",
                "doHaveRedirectionLink": null,
                "menuLink": "/view-seller",
                "isASubMenu": true,
                "canMasterAccess": null,
                "canAdminAccess": true,
                "canUserAccess": true,
                "canDoctorAccess": true,
                "canSellerAccess": true,
                "canRiderAccess": true,
                "chatUsersAccess": true,
                "isVisibleToGuest": true,
                "isAvailableWhileLoggedOut": true,
                "isAssignedToParentMenu": true,
                "listOfSubMenu": null
            },
            {
                "id": "194818a7-8602-42a7-acf6-2a5cdc935bc3",
                "menuName": "Doctor View",
                "doHaveRedirectionLink": null,
                "menuLink": "/view-doctor",
                "isASubMenu": true,
                "canMasterAccess": null,
                "canAdminAccess": true,
                "canUserAccess": true,
                "canDoctorAccess": true,
                "canSellerAccess": true,
                "canRiderAccess": true,
                "chatUsersAccess": true,
                "isVisibleToGuest": true,
                "isAvailableWhileLoggedOut": true,
                "isAssignedToParentMenu": true,
                "listOfSubMenu": null
            },
            {
                "id": "5e721d6e-71a3-45ce-8417-124ca726bd13",
                "menuName": "User View",
                "doHaveRedirectionLink": null,
                "menuLink": "/view-user",
                "isASubMenu": true,
                "canMasterAccess": null,
                "canAdminAccess": true,
                "canUserAccess": true,
                "canDoctorAccess": true,
                "canSellerAccess": true,
                "canRiderAccess": true,
                "chatUsersAccess": true,
                "isVisibleToGuest": true,
                "isAvailableWhileLoggedOut": true,
                "isAssignedToParentMenu": true,
                "listOfSubMenu": null
            }
        ]
    },
    {
        "id": "5caff3d3-b60e-49c6-9900-56eb01367e5b",
        "menuName": "About",
        "doHaveRedirectionLink": null,
        "menuLink": "/about",
        "isASubMenu": false,
        "canMasterAccess": null,
        "canAdminAccess": true,
        "canUserAccess": true,
        "canDoctorAccess": true,
        "canSellerAccess": true,
        "canRiderAccess": true,
        "chatUsersAccess": true,
        "isVisibleToGuest": true,
        "isAvailableWhileLoggedOut": true,
        "isAssignedToParentMenu": true,
        "listOfSubMenu": null
    },
    {
        "id": "9c535748-b80d-47a5-b492-9c4c5ce43587",
        "menuName": "Cotact Us",
        "doHaveRedirectionLink": null,
        "menuLink": "/cotact-us",
        "isASubMenu": false,
        "canMasterAccess": null,
        "canAdminAccess": true,
        "canUserAccess": true,
        "canDoctorAccess": true,
        "canSellerAccess": true,
        "canRiderAccess": true,
        "chatUsersAccess": true,
        "isVisibleToGuest": true,
        "isAvailableWhileLoggedOut": true,
        "isAssignedToParentMenu": true,
        "listOfSubMenu": null
    },
    {
        "id": "3621906f-24fb-479d-9ef5-5a1a30886f26",
        "menuName": "Master Dashboard",
        "doHaveRedirectionLink": null,
        "menuLink": null,
        "isASubMenu": false,
        "canMasterAccess": null,
        "canAdminAccess": true,
        "canUserAccess": true,
        "canDoctorAccess": true,
        "canSellerAccess": true,
        "canRiderAccess": true,
        "chatUsersAccess": true,
        "isVisibleToGuest": true,
        "isAvailableWhileLoggedOut": true,
        "isAssignedToParentMenu": true,
        "listOfSubMenu": [
            {
                "id": "c7614545-fcec-44a4-84b2-fe885d07b8b0",
                "menuName": "View Admins",
                "doHaveRedirectionLink": null,
                "menuLink": "/cotact-us",
                "isASubMenu": true,
                "canMasterAccess": null,
                "canAdminAccess": true,
                "canUserAccess": true,
                "canDoctorAccess": true,
                "canSellerAccess": true,
                "canRiderAccess": true,
                "chatUsersAccess": true,
                "isVisibleToGuest": true,
                "isAvailableWhileLoggedOut": true,
                "isAssignedToParentMenu": true,
                "listOfSubMenu": null
            }
        ]
    }
]
